# **UPDATED VERSION**
# ----------------

# Pandas case study
## We will check the data from kashti dataset

In [67]:
# import libarabries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [68]:
kashti= sns.load_dataset("titanic")
kashti

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [69]:
kashti.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

# Saving Dataframe into CSV file

In [70]:
kashti.to_csv("kashti.csv")

# Different comands on same dataset

## Describe

In [71]:
kashti.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [72]:
kashti.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

## Droping few columns and make a new dataset

In [73]:
new_kashti =kashti.drop(["deck","alone"], axis=1)
new_kashti.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no

In [74]:
kashti.drop(["deck","alone"], axis=1).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no

In [75]:
kashti.mean

<bound method NDFrame._add_numeric_operations.<locals>.mean of      survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
4           0       3    male  35.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female   NaN      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True  NaN  Southampton    no  False
1    woman       False    C    Cherbourg   yes  False
2    woman       False  NaN  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
4      man        True  NaN  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
886    man        True  NaN  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False  NaN  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]>

In [76]:
kashti.groupby("sex")["fare"].mean()

sex
female    44.479818
male      25.523893
Name: fare, dtype: float64

In [77]:
kashti.groupby("sex")["parch"].mean()

sex
female    0.649682
male      0.235702
Name: parch, dtype: float64

In [78]:
kashti.value_counts(["survived"])

survived
0           549
1           342
Name: count, dtype: int64

# To check data types for each column

In [79]:
print(kashti.dtypes)

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [80]:
kashti.groupby('sex')[['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare']].mean()

        survived    pclass        age     sibsp     parch       fare
sex
female  0.742038  2.159236  27.915709  0.694268  0.649682  44.479818
male    0.188908  2.389948  30.726645  0.429809  0.235702  25.523893

In [81]:
kashti.groupby("sex")[["fare","age"]].mean()

             fare        age
sex
female  44.479818  27.915709
male    25.523893  30.726645

In [82]:
kashti.groupby("sex")[["fare","age"]].mean()

             fare        age
sex
female  44.479818  27.915709
male    25.523893  30.726645

In [83]:
grouped = kashti.groupby('sex')  # 'sex' is a categorical column

# Children and women are 1st

In [84]:
# kashti[kashti ["age"]<18].mean() This was incorrect, instead of this

# do this

kashti[kashti["age"] < 18]['age'].mean()

9.04132743362832

In [85]:
filtered_kashti = kashti[kashti["age"] < 18]
grouped = filtered_kashti.groupby('sex')
mean_values = grouped.mean(numeric_only=True)
print(mean_values)

        survived    pclass       age     sibsp     parch       fare  \
sex
female  0.690909  2.490909  9.236364  1.200000  1.036364  32.782653
male    0.396552  2.672414  8.856379  1.706897  1.068966  29.739729

        adult_male     alone
sex
female    0.000000  0.200000
male      0.310345  0.206897

In [47]:
# kashti[kashti ["age"]< 18].groupby(["sex", "class"]).mean()  ** you tried to groupby categorical or non numeric features

In [86]:
# TO Filter the DataFrame to Include Only Numeric Data
numeric_colums = kashti.select_dtypes(include=[np.number])  # This selects only numeric columns

In [87]:
numeric_colums[kashti["age"] < 18].groupby(["fare", "pclass"]).mean()

                 survived    age     sibsp     parch
fare     pclass
7.0542   3       0.000000  17.00  1.000000  0.000000
7.1250   3       0.000000  17.00  0.000000  0.000000
7.2250   3       1.000000  15.00  0.000000  0.000000
7.2292   3       0.333333  15.00  0.666667  0.666667
7.7333   3       1.000000  16.00  0.000000  0.000000
...                   ...    ...       ...       ...
108.9000 1       1.000000  17.00  1.000000  0.000000
110.8833 1       1.000000  17.00  0.000000  2.000000
120.0000 1       1.000000  12.50  1.000000  2.000000
151.5500 1       0.500000   1.46  1.000000  2.000000
211.3375 1       1.000000  15.00  0.000000  1.000000

[69 rows x 4 columns]

In [88]:
print(kashti.columns)

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [89]:
kashti.groupby(['pclass', 'sex'])['fare'].mean()

pclass  sex
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: fare, dtype: float64

# Average Age by Passenger Class and Gender

In [90]:
kashti.groupby(['pclass', 'sex'])['age'].mean()

pclass  sex
1       female    34.611765
        male      41.281386
2       female    28.722973
        male      30.740707
3       female    21.750000
        male      26.507589
Name: age, dtype: float64

# Total Fare and Survival Rate by Embarkation Port

In [91]:
total_fare_and_survival = kashti.groupby('embark_town')[['fare', 'survived']].agg({
    'fare': 'sum',   # Total fare
    'survived': 'mean'  # Average survival rate
})
print(total_fare_and_survival)

                   fare  survived
embark_town
Cherbourg    10072.2962  0.553571
Queenstown    1022.2543  0.389610
Southampton  17439.3988  0.336957

# Maximum and Minimum Age by Class

In [92]:
kashti.groupby('pclass')['age'].agg(['max', 'min'])

         max   min
pclass
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

# Count of Passengers by Gender and Whether They Traveled Alone

In [93]:
kashti.groupby(['sex', 'alone'])['alone'].count()

sex     alone
female  False    188
        True     126
male    False    166
        True     411
Name: alone, dtype: int64